config/routes.rb
Rails.application.routes.draw do

  root to: "cocktails#index"

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :find_cocktail, only: [ :show ]

  def index
    @cocktails = Cocktail.all
  end

  def new
   @cocktail = Cocktail.new
  end
  def create
     @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path(@cocktail)
    else
      render :new
    end
  end

  def show
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :find_cocktail, only: [ :new, :create ]

  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params['id'])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end


private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails list</h1>

<% @cocktails.each do |cocktail| %>
<h2><%= cocktail.name %></h2>
<%= link_to 'Recipe', cocktail_path(cocktail) %>
<% end %><hr>

<%= link_to 'Add a cocktail', new_cocktail_path(@cocktail), class: "btn btn-primary" %>

app/views/cocktails/new.html.erb
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<h2><%= @cocktail.name %></h2>

<hr>
<ul>
<% @cocktail.doses.each do |dose| %>
<li><%= dose.description %> <%= dose.ingredient.name %></li>
<%= link_to 'Delete', dose_path(dose),
      method: :delete,
      data: { confirm: "Are you sure?" } %></br></br>

<%end%>
</ul>

<hr>

<%= link_to 'Add a dose of something', new_cocktail_dose_path(@cocktail) %></br>
<%= link_to 'Back to list', cocktails_path %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>